# Generated by Django 5.1 on 2024-09-01 22:00

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created time')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Book Name')),
                ('price', models.BigIntegerField(verbose_name='Price')),
                ('quantity', models.IntegerField(verbose_name='Quantity of available books')),
                ('published_at', models.DateField(default=datetime.date.today, verbose_name='Date of book publish')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last time Modified')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created time')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.author', verbose_name='Author')),
            ],
        ),
    ]
